### ISSUE TITLE
generalised tree growing 

### ISSUE THREAD

**Issue by tawhai** [LungNoodle/lungsim#117]
adapting the call to grow_tree to give a list of surface elements to grow into (instead of all elements). adding curved surfaces to the triangularisation that is used for make_data_grid and for checking whether a generated branch is inside the surface element list.

**Comment by tawhai** [comment]
- requires the bindings to be adapted to include a list of surface elements. currently not working correctly when the call is from the grow tree module (works from geometry which has similar bindings for other subroutines.
- have had to do some reassignment of subroutines/functions from geometry to mesh_utilities
- bug in make_data_grid to do with triangles_from_surface. Some elements have no triangles created which allows the data grid to 'leak' outside of the surfaces.

**Comment by behdadebsh** [comment]
Does this issue include any code updates on element mapping to seed data points? Double checking to conflicts with issue #92

**Comment by tawhai** [comment]
It doesn't explicitly resolve that issue. We should only be exporting information that is held in a nodal or element field. Otherwise it should be a file write. If you want this exported I suggest that you put it into an element field and then export from the python script.

**Comment by behdadebsh** [comment]
@tawhai is this solved now?

**Comment by tawhai** [comment]
yes this has been resolved.
