### ISSUE TITLE
using a target number of data points

### ISSUE THREAD

**Issue by tawhai** [LungNoodle/lungsim#156]
current data point grid creation relies on the user entering a spacing value. add an option of specifying a target number of data points that will start by using the cube root of volume/n_target_data

**Comment by behdadebsh** [comment]
While using STLs to grow a tree, it is fairly easy to calculate the volume of the surface mesh using PyVista and include the target number of points within the script. That's how I do it at the moment.

**Comment by tawhai** [comment]
1.  Not all trees are grown within STLs.
  2.  When growing within STLs or other meshes the number of data points can be way off what is expected.

Professor Merryn H. Tawhai, FRSNZ
Manutaki | Director, Auckland Bioengineering Institute
Waipapa Taumata Rau | University of Auckland, New Zealand


From: Behdad Shaarbaf Ebrahimi ***@***.***>
Date: Friday, 15 December 2023 at 2:41 PM
To: LungNoodle/lungsim ***@***.***>
Cc: Merryn Tawhai ***@***.***>, Author ***@***.***>
Subject: Re: [LungNoodle/lungsim] using a target number of data points (Issue #156)

While using STLs to grow a tree, it is fairly easy to calculate the volume of the surface mesh using PyVista and include the target number of points within the script. That's how I do it at the moment.

**Comment by tawhai** [comment]
Issue resolved as of 25/1/24. New option to specify number of target seed points.
