### ISSUE TITLE
Outlier points generated by make_data_grid()

### ISSUE THREAD

**Issue by Megan-Soo** [LungNoodle/lungsim#160]
make_data_grid() function in aether creates anomalous points when generating point cloud from .ply file.

**LEFT** 
- ply mesh

**RIGHT**
- white points are node points generated from ply mesh by export_triangle_nodes()
- blue points are data points generated from ply mesh by make_data_grid()

_Examples of point clouds extracted from lobe meshes_
![RLL](https://github.com/LungNoodle/lungsim/assets/146890233/cbbe8744-2b46-4218-80fe-9a00785f7c78)
![LUL](https://github.com/LungNoodle/lungsim/assets/146890233/48199b93-5aeb-4b3e-91b2-0c147cc98fe2)
![LLL](https://github.com/LungNoodle/lungsim/assets/146890233/a4aa217f-71ac-4529-a800-5df00f539264)
![RUL](https://github.com/LungNoodle/lungsim/assets/146890233/873f766a-baa0-488d-b6ce-92b915dfa95c)

_one data cloud with no outlier_
![RML](https://github.com/LungNoodle/lungsim/assets/146890233/290049c0-153b-4178-993a-01da686faf05)

Parameters used for make_data_grid():
- peel = 5.0
- spacing = [3.42, 3.18, 2.95, 3.47, 2.95]; # [RUL, RML, RLL, LUL, LLL]

**Comment by tawhai** [comment]
Issue should be resolved by recent pull request. please check

**Comment by behdadebsh** [comment]
@Megan-Soo

**Comment by Megan-Soo** [comment]
The update works fine, no outlier points in the new cloud, thank you.
![image](https://github.com/LungNoodle/lungsim/assets/146890233/3325d724-5fb9-4df7-aa97-682cbc2ab9b4)
Left - old make_data_grid()
Right - updated make_data_grid()

**Comment by behdadebsh** [comment]
Thanks, Megan.
