### ISSUE TITLE
Sphinx-fortran component of docs searching for incorrect file path

### ISSUE THREAD

**Issue by alysclark** [LungNoodle/lungsim#30]
fortran_src in conf.py for documentation appears to be hard coded to search for legacy locations of src. Need to generalise

fortran_src = ['/people/acla148/lung/NEONlung/Library/src/arrays.f90','/people/acla148/lung/NEONlung/Library/src/geometry.f90']

**Comment by hsorby** [comment]
How did that get past the review process?

**Comment by alysclark** [comment]
Suspect it has been there since the first commit (or some terrible reviewing)!
